# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:23
from __future__ import unicode_literals
from django.db import migrations


def migrate_images(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    WagtailImages = apps.get_model("wagtailimages", "Image")
    for image in WagtailImages.objects.all():
        flis_image = apps.get_model("pages", "FlisImage")()
        flis_image.title = image.title
        flis_image.file = image.file
        flis_image.width = image.width
        flis_image.height = image.height
        flis_image.created_at = image.created_at
        flis_image.uploaded_by_user = image.uploaded_by_user
        flis_image.pk = image.pk
        flis_image.save()


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0002_auto_20170303_1018'),
    ]

    operations = [
        migrations.RunPython(migrate_images),
    ]
