# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0003_auto_20170303_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='pages.FlisImage'),
        ),
        migrations.AlterField(
            model_name='staticindex',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='pages.FlisImage'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='pages.FlisImage'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='pages.FlisImage'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='pages.FlisImage'),
        ),
    ]
