# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:29
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0004_auto_20170303_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticindex',
            name='allowed_subpage_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[
                ('flis_horison_scanning.Signal', 'flis_horison_scanning.Signal'),
                ('flis_flip.Assesment', 'flis_flip.Assesment'),
                ('flis_flip.ForwardLookingActivity', 'flis_flip.ForwardLookingActivity')], max_length=81, null=True),
        ),
    ]
