# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0009_auto_20170403_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
