# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0002_auto_20170303_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverofchange',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='pages.FlisImage'),
        ),
    ]
