# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0004_auto_20170303_1045'),
        ('flis_metadata', '0001_initial'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('flis_horison_scanning', '0003_auto_20170303_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEAIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='OriginOfSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverallImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('short_title', models.CharField(max_length=256)),
                ('type_of_signal', models.CharField(
                    choices=[('megatrend', 'Megatrend'), ('trend', 'Trend'), ('weak_signal', 'Weak Signal'),
                             ('wild_card', 'Wild Card'), ('other', 'Other')], max_length=64)),
                ('headline', models.TextField(max_length=256)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
                ('impact_description', wagtail.wagtailcore.fields.RichTextField()),
                ('implications', wagtail.wagtailcore.fields.RichTextField()),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='+', to='pages.FlisImage')),
                ('geographical_scope',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='flis_metadata.GeographicalScope')),
                ('overall_impact',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='flis_horison_scanning.OverallImpact')),
                ('time_horizon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='flis_horison_scanning.TimeHorizon')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SignalSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', wagtail.wagtailcore.fields.RichTextField()),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_sources',
                                             to='flis_horison_scanning.Signal')),
            ],
        ),
        migrations.AlterModelOptions(
            name='driverofchange',
            options={'verbose_name': 'Signal of Change', 'verbose_name_plural': 'Signals of Change'},
        ),
        migrations.AddField(
            model_name='eeaindicator',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eea_indicators',
                                    to='flis_horison_scanning.Signal'),
        ),
    ]
