# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0004_auto_20170314_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eeaindicator',
            name='signal',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='eea_indicators', to='flis_horison_scanning.Signal'),
        ),
        migrations.AlterField(
            model_name='signalsource',
            name='signal',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='signal_sources', to='flis_horison_scanning.Signal'),
        ),
    ]
