# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0006_timehorizon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='origin_of_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='flis_horison_scanning.OriginOfSignal'),
        ),
    ]
