# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0007_signal_origin_of_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicalScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='signal',
            name='geographical_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='flis_horison_scanning.GeographicalScope'),
        ),
    ]
