# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0010_auto_20170316_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofsignal',
            name='slug',
            field=models.SlugField(editable=False, primary_key=True, serialize=False),
        ),
    ]
