# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0011_auto_20170316_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='type_of_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='flis_horison_scanning.TypeOfSignal'),
        ),
    ]
