# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0013_auto_20170316_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofsignal',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
