# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0015_auto_20170316_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofsignal',
            name='sort_order',
        ),
    ]
