# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0018_geographicalscope_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='originofsignal',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overallimpact',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timehorizon',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
