# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0005_auto_20170314_1629'),
        ('flis_horison_scanning', '0019_auto_20170316_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='+', to='pages.FlisImage')),
                ('signal',
                 modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                                 to='flis_horison_scanning.Signal')),
            ],
        ),
    ]
