# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0020_signalimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eeaindicator',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='originofsignal',
            options={'verbose_name': 'Origin of Signal', 'verbose_name_plural': 'Origins of Signals'},
        ),
        migrations.AlterModelOptions(
            name='signalimage',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='signalsource',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='typeofsignal',
            options={'verbose_name_plural': 'Types of Signals'},
        ),
        migrations.AlterField(
            model_name='signal',
            name='impact_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='implications',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='type_of_signal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='flis_horison_scanning.TypeOfSignal'),
        ),
    ]
