# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('flis_horison_scanning', '0021_auto_20170320_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='EUStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelevanceOfSignalLikelihood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelevanceOfSignalSeverity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ('-first_published_at',)},
        ),
        migrations.AddField(
            model_name='signal',
            name='date_of_signal_detection',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem',
                                                  to='taggit.Tag', verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='signal',
            name='likelihood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='flis_horison_scanning.RelevanceOfSignalLikelihood'),
        ),
        migrations.AddField(
            model_name='signal',
            name='severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='flis_horison_scanning.RelevanceOfSignalSeverity'),
        ),
        migrations.AddField(
            model_name='signal',
            name='strategies',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='flis_horison_scanning.EUStrategy'),
        ),
    ]
