# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0022_auto_20170403_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='Date of last modification to the signal',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
