# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0023_signal_date of last modification to the signal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='Date of last modification to the signal',
        ),
        migrations.AddField(
            model_name='signal',
            name='date_of_last_modification',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date of last modification to the signal'),
        ),
    ]
