# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('flis_horison_scanning', '0024_auto_20170403_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='signal',
            name='date_of_last_modification',
            field=models.DateField(null=True, verbose_name='Date of last modification to the signal'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True,
                                                                     help_text='A comma-separated list of tags.',
                                                                     through='flis_horison_scanning.SignalTag',
                                                                     to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='signaltag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='tagged_signals', to='flis_horison_scanning.Signal'),
        ),
        migrations.AddField(
            model_name='signaltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='flis_horison_scanning_signaltag_items', to='taggit.Tag'),
        ),
    ]
