# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flis_horison_scanning', '0027_auto_20170403_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signaltagitem',
            options={'ordering': ('name',)},
        ),
    ]
