version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  media_data: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
      - ./compose/postgres/postgresql.conf:/etc/postgresql.conf
    env_file: .env

  django:
    build: .
    volumes:
      - media_data:/app/media
      - /app/staticfiles
    user: django
    depends_on:
      - postgres
      - redis
      - mailservice
    env_file: .env
    environment:
      EMAIL_HOST: mailservice

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    volumes_from:
      - django

  redis:
    image: redis:alpine

  mailservice:
    image: marcelesser/smtp-sink:latest

