# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:49
from __future__ import unicode_literals

from django.db import migrations
import pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0002_auto_20170303_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicstorypage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('subheading',
                                                           wagtail.wagtailcore.blocks.CharBlock(classname='full title',
                                                                                                icon='title',
                                                                                                template='pages/streamfield_blocks/subheading.html')),
                                                          ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (
                                                          'image_with_caption', wagtail.wagtailcore.blocks.StructBlock((
                                                                                                                       (
                                                                                                                       'image',
                                                                                                                       wagtail.wagtailimages.blocks.ImageChooserBlock(
                                                                                                                           required=True)),
                                                                                                                       (
                                                                                                                       'caption',
                                                                                                                       wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                           required=False)),
                                                                                                                       (
                                                                                                                       'image_width',
                                                                                                                       wagtail.wagtailcore.blocks.ChoiceBlock(
                                                                                                                           choices=[
                                                                                                                               (
                                                                                                                               'content_wide',
                                                                                                                               'Content wide'),
                                                                                                                               (
                                                                                                                               'page_wide',
                                                                                                                               'Page wide')]))))),
                                                          ('footnotes', wagtail.wagtailcore.blocks.StructBlock(((
                                                                                                                'notes',
                                                                                                                wagtail.wagtailcore.blocks.ListBlock(
                                                                                                                    wagtail.wagtailcore.blocks.RichTextBlock(
                                                                                                                        required=True))),))),
                                                          ('table_with_header', wagtail.wagtailcore.blocks.StructBlock((
                                                                                                                       (
                                                                                                                       'number',
                                                                                                                       wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                           title='Table number')),
                                                                                                                       (
                                                                                                                       'title',
                                                                                                                       wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                           title='Table title')),
                                                                                                                       (
                                                                                                                       'table',
                                                                                                                       pages.blocks.UpdatedTableBlock(
                                                                                                                           required=True,
                                                                                                                           table_options={
                                                                                                                               'autoColumnSize': False,
                                                                                                                               'colHeaders': False,
                                                                                                                               'contextMenu': True,
                                                                                                                               'editor': 'text',
                                                                                                                               'height': 150,
                                                                                                                               'mergeCells': True,
                                                                                                                               'minSpareRows': 0,
                                                                                                                               'renderer': 'text',
                                                                                                                               'rowHeaders': False,
                                                                                                                               'startCols': 4,
                                                                                                                               'startRows': 4,
                                                                                                                               'stretchH': 'all'})))))),
                                                         blank=True),
        ),
    ]
