# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:09
from __future__ import unicode_literals

from django.db import migrations
import pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0011_auto_20170419_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicstorypage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('image_with_caption', wagtail.wagtailcore.blocks.StructBlock(
                (('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)),
                 ('caption', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('image_width',
                                                                                     wagtail.wagtailcore.blocks.ChoiceBlock(
                                                                                         choices=[('content_wide',
                                                                                                   'Content wide'), (
                                                                                                  'page_wide',
                                                                                                  'Page wide')]))))), (
                                                          'footnotes', wagtail.wagtailcore.blocks.StructBlock((('notes',
                                                                                                                wagtail.wagtailcore.blocks.ListBlock(
                                                                                                                    wagtail.wagtailcore.blocks.RichTextBlock(
                                                                                                                        required=True))),))),
                                                          ('nexus_graph', wagtail.wagtailcore.blocks.StructBlock(((
                                                                                                                  'block_heading',
                                                                                                                  wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                      required=True)),
                                                                                                                  (
                                                                                                                  'top_title',
                                                                                                                  wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                      required=True)),
                                                                                                                  (
                                                                                                                  'top_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'top_to_left_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'top_to_right_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'right_title',
                                                                                                                  wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                      required=True)),
                                                                                                                  (
                                                                                                                  'right_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'right_to_top_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'right_to_left_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'left_title',
                                                                                                                  wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                      required=True)),
                                                                                                                  (
                                                                                                                  'left_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'left_to_right_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'left_to_top_description',
                                                                                                                  wagtail.wagtailcore.blocks.TextBlock(
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'read_more_button',
                                                                                                                  wagtail.wagtailcore.blocks.StructBlock(
                                                                                                                      ((
                                                                                                                       'label',
                                                                                                                       wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                           default='Find out more',
                                                                                                                           required=False)),
                                                                                                                       (
                                                                                                                       'page',
                                                                                                                       wagtail.wagtailcore.blocks.PageChooserBlock(
                                                                                                                           required=False))),
                                                                                                                      required=False))))),
                                                          ('table_with_header', wagtail.wagtailcore.blocks.StructBlock((
                                                                                                                       (
                                                                                                                       'number',
                                                                                                                       wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                           required=False,
                                                                                                                           title='Table number')),
                                                                                                                       (
                                                                                                                       'title',
                                                                                                                       wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                           required=False,
                                                                                                                           title='Table title')),
                                                                                                                       (
                                                                                                                       'table',
                                                                                                                       pages.blocks.UpdatedTableBlock(
                                                                                                                           required=True,
                                                                                                                           table_options={
                                                                                                                               'autoColumnSize': False,
                                                                                                                               'colHeaders': False,
                                                                                                                               'contextMenu': True,
                                                                                                                               'editor': 'text',
                                                                                                                               'height': 150,
                                                                                                                               'mergeCells': True,
                                                                                                                               'minSpareRows': 0,
                                                                                                                               'renderer': 'text',
                                                                                                                               'rowHeaders': False,
                                                                                                                               'startCols': 4,
                                                                                                                               'startRows': 4,
                                                                                                                               'stretchH': 'all'}))))),
                                                          ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (
                                                          'subheading',
                                                          wagtail.wagtailcore.blocks.CharBlock(classname='full title',
                                                                                               icon='title',
                                                                                               template='pages/streamfield_blocks/subheading.html')),
                                                          ('video_embed', wagtail.wagtailcore.blocks.StructBlock(
                                                              (('embed', pages.blocks.VideoEmbedFieldBlock()),)))),
                                                         blank=True),
        ),
    ]
