COLORS = [
    ('aqua', 'Aqua'),
    ('black', 'Black'),
    ('cherry', 'Cherry'),
    ('lime', 'Lime'),
    ('purple', 'Purple'),
    ('orange', 'Orange'),
    ('red', 'Red'),
]

ICONS = [
    ('book', 'Book'),
    ('chart', 'Chart'),
    ('clusters', 'Clusters'),
    ('counter', 'Counter'),
    ('cutlery', 'Cutlery'),
    ('database', 'Database'),
    ('drop', 'Drop'),
    ('eye', 'Eye'),
    ('glasses', 'Glasses'),
    ('indicator', 'Indicator'),
    ('lighting', 'Lightning'),
    ('diamond', 'Note'),
    ('puzzle', 'Puzzle'),
    ('road-signs', 'Road Signs'),
    ('stack', 'Stack'),
    ('strategy', 'Strategy'),
    ('sunset', 'Sunset'),
    ('target', 'Target'),
    ('upload', 'Upload'),
    ('users-leader', 'Users'),
]
